package com.scottejames.downsman.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.scottejames.downsman.services.ScoutService;
import com.scottejames.downsman.services.SupportService;

import java.util.ArrayList;
import java.util.List;


@DynamoDBTable(tableName = "Team")
public class TeamModel  {

    private String ownerID = null;
    private String id = null;
    private String teamName = null;
    private String hikeClass = null;
    private String section = null;
    private String district = null;
    private String county = null;
    private String activeMobile = null;
    private String backupMobile = null;
    private String emergencyContactName = null;
    private String emergencyContactMobile = null;
    private String emergencyContactLandline = null;
    private String emergencyContactEmail = null;
    private String leaderName = null;
    private boolean paymentRecieved = false;
    private boolean teamSubmitted = false;
    private boolean campingAtStart = false;



    private final ScoutService scoutService = new ScoutService();
    private final SupportService supportService = new SupportService();
    public TeamModel(){

    }
    public TeamModel(String ownerID, String teamName) {
        this.ownerID = ownerID;
        this.teamName = teamName;
    }

    public TeamModel(String ownerID,String teamName, String hikeClass) {
        this.ownerID = ownerID;
        this.teamName = teamName;
        this.hikeClass = hikeClass;
    }
    public TeamModel(String ownerID,
                     String teamName,
                     String hikeClass,
                     String status,
                     String section,
                     String district,
                     String county,
                     String activeMobile,
                     String backupMobile,
                     String emergencyContactName,
                     String emergencyContactMobile,
                     String emergencyContactLandline) {
        this.ownerID = ownerID;
        this.teamName = teamName;
        this.hikeClass = hikeClass;
        this.section = section;
        this.district = district;
        this.county = county;
        this.activeMobile = activeMobile;
        this.backupMobile = backupMobile;
        this.emergencyContactName = emergencyContactName;
        this.emergencyContactMobile = emergencyContactMobile;
        this.emergencyContactLandline = emergencyContactLandline;
    }

    @DynamoDBIgnore
    public void addScoutMember(ScoutModel scout){
        scout.setOwnerID(id);
        if (scout.isPersisted())
            scoutService.update(scout);
        else
            scoutService.add(scout);
    }
    @DynamoDBIgnore
    public void addSupportMember(SupportModel support){
        support.setOwnerID(id);
        if (support.isPersisted())
            supportService.update((support));
        else
            supportService.add((support));

    }
    @DynamoDBIgnore
    public List<ScoutModel> getScoutsTeam(){
        if (this.getId() == null) // if i dont have an id i have not been saved so cant have any scouts
            return null;
        else
            return scoutService.getAll(this.getId());
    }
    @DynamoDBIgnore
    public List<SupportModel> getSupportTeam(){
        if (this.getId() == null) // if i dont have an id i have not been saved so cant have any support
            return null;
        else
            return supportService.getAll(getId());
    }
    @DynamoDBIgnore
    public void removeScoutMember(ScoutModel scout){

        scoutService.remove(scout);
        scout.setOwnerID(null);
    }
    @DynamoDBIgnore
    public void removeSupportMember(SupportModel support){

        supportService.remove(support);
        support.setOwnerID(null);
    }

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    public String getId(){ return id;}
    public void setId(String id){ this.id = id;}

    @DynamoDBHashKey
    public String getOwnerID() { return ownerID; }
    public void setOwnerID(String ownerID) { this.ownerID = ownerID;}

    @DynamoDBAttribute
    public boolean isPaymentRecieved() {
        return paymentRecieved;
    }
    public void setPaymentRecieved(boolean paymentRecieved) {
        this.paymentRecieved = paymentRecieved;
    }

    @DynamoDBAttribute
    public boolean isTeamSubmitted() {
        return teamSubmitted;
    }
    public void setTeamSubmitted(boolean teamSubmitted) {
        this.teamSubmitted = teamSubmitted;
    }

    @DynamoDBAttribute
    public String getEmergencyContactLandline() { return emergencyContactLandline; }
    public void setEmergencyContactLandline(String emergencyContactLandline) {
        this.emergencyContactLandline = emergencyContactLandline;
    }

    @DynamoDBAttribute
    public String getEmergencyContactEmail() {
        return emergencyContactEmail;
    }
    public void setEmergencyContactEmail(String emergencyContactEmail) {
        this.emergencyContactEmail = emergencyContactEmail;
    }

    @DynamoDBAttribute
    public String getSection() {
        return section;
    }
    public void setSection(String section) {
        this.section = section;
    }

    @DynamoDBAttribute
    public String getDistrict() { return district; }
    public void setDistrict(String district) {
        this.district = district;
    }

    @DynamoDBAttribute
    public String getCounty() {
        return county;
    }
    public void setCounty(String county) {
        this.county = county;
    }

    @DynamoDBAttribute
    public String getActiveMobile() {
        return activeMobile;
    }
    public void setActiveMobile(String activeMobile) {
        this.activeMobile = activeMobile;
    }

    @DynamoDBAttribute
    public String getBackupMobile() {
        return backupMobile;
    }
    public void setBackupMobile(String backupMobile) {
        this.backupMobile = backupMobile;
    }

    @DynamoDBAttribute
    public String getEmergencyContactName() {
        return emergencyContactName;
    }
    public void setEmergencyContactName(String emergencyContactName) {
        this.emergencyContactName = emergencyContactName;
    }

    @DynamoDBAttribute
    public String getEmergencyContactMobile() {
        return emergencyContactMobile;
    }
    public void setEmergencyContactMobile(String emergencyContactMobile) {
        this.emergencyContactMobile = emergencyContactMobile;
    }

    @DynamoDBAttribute
    public String getTeamName() {
        return teamName;
    }
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    @DynamoDBAttribute
    public String getHikeClass() {
        return hikeClass;
    }
    public void setHikeClass(String hikeClass) {
        this.hikeClass = hikeClass;
    }

    @DynamoDBAttribute
    public String getLeaderName() {
        return leaderName;
    }
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName;
    }

    @DynamoDBAttribute
    public boolean isCampingAtStart() {
        return campingAtStart;
    }

    public void setCampingAtStart(boolean campingAtStart) {
        this.campingAtStart = campingAtStart;
    }

    @DynamoDBIgnore
    public boolean isPersisted() {
        if (id == null) return false;
        else return true;
    }


    @DynamoDBIgnore
    public String getSubmittedStatus(){
        if (teamSubmitted) {
            return "Submitted";
        } else {
            return "Not Submitted";
        }

    }
    @DynamoDBIgnore
    public String getPaymentStatus(){
        if (paymentRecieved) {
            return "Paid";
        } else {
            return "Not Paid";
        }
    }

    @DynamoDBIgnore
    public String toString() {
        return "Team : " + teamName + " Hike class " + hikeClass;
    }
}

