package com.scottejames.downsman.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.scottejames.downsman.utils.HashHelper;

import java.sql.Ref;

@DynamoDBTable(tableName = "User")
public class UserModel {

    private String username = null;
    private String password = null;
    private Boolean admin = false;
    private String id = null;
    public UserModel(){

    }
    public UserModel(String u, String p) {
        username = u;
        if (p!=null)
            password = HashHelper.hashPassword(p);
    }

    @DynamoDBRangeKey
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    @DynamoDBHashKey
    public String getOwnerID() { return "None"; }
    public void setOwnerID(String ownerID) {;}

    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute
    public Boolean isAdmin() {
        return admin;
    }
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    @DynamoDBAutoGeneratedKey
    public String getId(){ return id;}
    public void setId(String id){ this.id = id;}

    @DynamoDBIgnore
    public boolean isPersisted() {
        if (id == null) return false;
        else return true;
    }

    public String toString(){
        return " U : " + username + " P : " + password;
    }


}
