version: '2'
services:
  web:
   image:  scottejames/downsman:2.2
   ports:
    - "80:8080"
    - "443:8443"
   volumes:
    - /Users/scottejames/certs/letsencrypt:/etc/letsencrypt
   environment:
    - DM_DEV=true
  database:
   image: amazon/dynamodb-local 
   command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
   ports: 
     - "8000:8000"
   volumes:
     - ~/tmp/data:/data
   environment:
    - AWS_REGION="eu-west-2"
